In [ ]:
import numpy as np
arr=np.array([[[2,3,4],[5,6,7]],[[2,3,4],[5,6,7],],[[2,3,4],[5,6,7]]])
print(arr)
print(arr.shape)
print(arr.ndim)
print(arr.size)
ar=np.arange(24).reshape(6,4)
print(ar)

[[[2 3 4]
  [5 6 7]]

 [[2 3 4]
  [5 6 7]]

 [[2 3 4]
  [5 6 7]]]
(3, 2, 3)
3
18
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [ ]:
(ar.resize(8,3))
print(ar)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]


In [ ]:
print(ar.dtype)

int64


In [ ]:
a=np.array([[[2,3,4],[5,6,7]],[[2,3,4],[5,6,7],],[[2,3,4],[5,6,7]]],dtype=complex) 
print(a.dtype)

complex128


In [ ]:
e=np.empty((2,3,4))
print(e)

[[[4.66679824e-310 7.21335843e-322 0.00000000e+000 0.00000000e+000]
  [0.00000000e+000 3.16251369e+180 1.05776693e-153 6.03461190e+151]
  [7.67951336e-043 1.29060660e+248 8.42244190e+252 1.05250177e-153]]

 [[3.98472821e+252 3.62633720e+228 4.27255699e+180 8.80088569e+199]
  [1.16267760e-028 2.04794095e+161 7.33729745e+223 5.28964318e+180]
  [5.03734623e+180 3.99910946e+252 3.19854319e+209 1.58268989e-319]]]


In [ ]:
e=np.ones((2,3),dtype=np.int16)
print(e)

[[1 1 1]
 [1 1 1]]


In [ ]:
print(e.size)
print(e.shape)
print(e.ndim)


6
(2, 3)
2


In [ ]:
print(np.linspace(1,2,3))
print(np.random)
p=e.flatten()
print(p)
print(np.arange(0,60,10).reshape(2,3))
l=np.random.random((2,3))
print(l)
k=np.zeros((4,5))
print(k)

[1.  1.5 2. ]
<module 'numpy.random' from '/usr/local/lib/python3.7/dist-packages/numpy/random/__init__.py'>
[1 1 1 1 1 1]
[[ 0 10 20]
 [30 40 50]]
[[0.74270169 0.32991503 0.80818335]
 [0.41519015 0.04295477 0.1280054 ]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
